# Generated by Django 3.1.3 on 2020-11-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('dishname', models.CharField(max_length=100)),
                ('stylename', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('people', models.IntegerField(default=1)),
                ('address', models.TextField()),
                ('create_date', models.DateTimeField()),
            ],
        ),
    ]
