# Generated by Django 3.1.3 on 2020-11-30 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinnername', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishname', models.TextField()),
                ('dishtype', models.TextField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tableware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablewarename', models.TextField()),
                ('tablewaretype', models.TextField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stylename', models.TextField()),
                ('price', models.IntegerField()),
                ('tablewares', models.ManyToManyField(to='myorder.Tableware')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('details', models.TextField()),
                ('people', models.IntegerField(default=1)),
                ('address', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('dinner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myorder.dinner')),
                ('style', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myorder.style')),
            ],
        ),
        migrations.AddField(
            model_name='dinner',
            name='appliablestyle',
            field=models.ManyToManyField(to='myorder.Style'),
        ),
        migrations.AddField(
            model_name='dinner',
            name='dishes',
            field=models.ManyToManyField(to='myorder.Dish'),
        ),
    ]
