# Generated by Django 3.1.3 on 2020-11-29 08:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myorder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishname', models.TextField()),
                ('dishtype', models.TextField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tableware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablewarename', models.TextField()),
                ('tablewaretype', models.TextField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='dishname',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stylename',
        ),
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stylename', models.TextField()),
                ('price', models.IntegerField()),
                ('tablewares', models.ManyToManyField(to='myorder.Tableware')),
            ],
        ),
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinnername', models.TextField()),
                ('appliablestyle', models.TextField()),
                ('price', models.IntegerField()),
                ('dishes', models.ManyToManyField(to='myorder.Dish')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='dinner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myorder.dinner'),
        ),
        migrations.AddField(
            model_name='order',
            name='style',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myorder.style'),
        ),
    ]
