# Generated by Django 3.1.3 on 2020-11-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myorder', '0002_auto_20201129_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinner',
            name='appliablestyle',
        ),
        migrations.AddField(
            model_name='dinner',
            name='appliablestyle',
            field=models.ManyToManyField(to='myorder.Style'),
        ),
    ]
